//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteNW.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NodoABB", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class NodoABB : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        private int conectadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteNW.ServiceReference1.NodoABB izqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteNW.ServiceReference1.NodoABB derField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteNW.ServiceReference1.ListaJuegos juegosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nickname {
            get {
                return this.nicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.nicknameField, value) != true)) {
                    this.nicknameField = value;
                    this.RaisePropertyChanged("nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int conectado {
            get {
                return this.conectadoField;
            }
            set {
                if ((this.conectadoField.Equals(value) != true)) {
                    this.conectadoField = value;
                    this.RaisePropertyChanged("conectado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ClienteNW.ServiceReference1.NodoABB izq {
            get {
                return this.izqField;
            }
            set {
                if ((object.ReferenceEquals(this.izqField, value) != true)) {
                    this.izqField = value;
                    this.RaisePropertyChanged("izq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ClienteNW.ServiceReference1.NodoABB der {
            get {
                return this.derField;
            }
            set {
                if ((object.ReferenceEquals(this.derField, value) != true)) {
                    this.derField = value;
                    this.RaisePropertyChanged("der");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ClienteNW.ServiceReference1.ListaJuegos juegos {
            get {
                return this.juegosField;
            }
            set {
                if ((object.ReferenceEquals(this.juegosField, value) != true)) {
                    this.juegosField = value;
                    this.RaisePropertyChanged("juegos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaJuegos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ListaJuegos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceNavalWarsSoap")]
    public interface ServiceNavalWarsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iniciarEstructuras", ReplyAction="*")]
        void iniciarEstructuras();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iniciarEstructuras", ReplyAction="*")]
        System.Threading.Tasks.Task iniciarEstructurasAsync();
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logearUsuario", ReplyAction="*")]
        ClienteNW.ServiceReference1.logearUsuarioResponse logearUsuario(ClienteNW.ServiceReference1.logearUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logearUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteNW.ServiceReference1.logearUsuarioResponse> logearUsuarioAsync(ClienteNW.ServiceReference1.logearUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarUsuario", ReplyAction="*")]
        ClienteNW.ServiceReference1.insertarUsuarioResponse insertarUsuario(ClienteNW.ServiceReference1.insertarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteNW.ServiceReference1.insertarUsuarioResponse> insertarUsuarioAsync(ClienteNW.ServiceReference1.insertarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarUsuario", ReplyAction="*")]
        ClienteNW.ServiceReference1.eliminarUsuarioResponse eliminarUsuario(ClienteNW.ServiceReference1.eliminarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteNW.ServiceReference1.eliminarUsuarioResponse> eliminarUsuarioAsync(ClienteNW.ServiceReference1.eliminarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarUsuario", ReplyAction="*")]
        ClienteNW.ServiceReference1.buscarUsuarioResponse buscarUsuario(ClienteNW.ServiceReference1.buscarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteNW.ServiceReference1.buscarUsuarioResponse> buscarUsuarioAsync(ClienteNW.ServiceReference1.buscarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name nicknameActual from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarUsuario", ReplyAction="*")]
        ClienteNW.ServiceReference1.ModificarUsuarioResponse ModificarUsuario(ClienteNW.ServiceReference1.ModificarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteNW.ServiceReference1.ModificarUsuarioResponse> ModificarUsuarioAsync(ClienteNW.ServiceReference1.ModificarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name enOrdenResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enOrden", ReplyAction="*")]
        ClienteNW.ServiceReference1.enOrdenResponse enOrden(ClienteNW.ServiceReference1.enOrdenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enOrden", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteNW.ServiceReference1.enOrdenResponse> enOrdenAsync(ClienteNW.ServiceReference1.enOrdenRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarHistorialJuego", ReplyAction="*")]
        ClienteNW.ServiceReference1.insertarHistorialJuegoResponse insertarHistorialJuego(ClienteNW.ServiceReference1.insertarHistorialJuegoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarHistorialJuego", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteNW.ServiceReference1.insertarHistorialJuegoResponse> insertarHistorialJuegoAsync(ClienteNW.ServiceReference1.insertarHistorialJuegoRequest request);
        
        // CODEGEN: Generating message contract since element name unidad from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarEnOrtogonal", ReplyAction="*")]
        ClienteNW.ServiceReference1.insertarEnOrtogonalResponse insertarEnOrtogonal(ClienteNW.ServiceReference1.insertarEnOrtogonalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarEnOrtogonal", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteNW.ServiceReference1.insertarEnOrtogonalResponse> insertarEnOrtogonalAsync(ClienteNW.ServiceReference1.insertarEnOrtogonalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logearUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logearUsuario", Namespace="http://tempuri.org/", Order=0)]
        public ClienteNW.ServiceReference1.logearUsuarioRequestBody Body;
        
        public logearUsuarioRequest() {
        }
        
        public logearUsuarioRequest(ClienteNW.ServiceReference1.logearUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logearUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        public logearUsuarioRequestBody() {
        }
        
        public logearUsuarioRequestBody(string nickname) {
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logearUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logearUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteNW.ServiceReference1.logearUsuarioResponseBody Body;
        
        public logearUsuarioResponse() {
        }
        
        public logearUsuarioResponse(ClienteNW.ServiceReference1.logearUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logearUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string logearUsuarioResult;
        
        public logearUsuarioResponseBody() {
        }
        
        public logearUsuarioResponseBody(string logearUsuarioResult) {
            this.logearUsuarioResult = logearUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public ClienteNW.ServiceReference1.insertarUsuarioRequestBody Body;
        
        public insertarUsuarioRequest() {
        }
        
        public insertarUsuarioRequest(ClienteNW.ServiceReference1.insertarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int conectado;
        
        public insertarUsuarioRequestBody() {
        }
        
        public insertarUsuarioRequestBody(string nickname, string password, string email, int conectado) {
            this.nickname = nickname;
            this.password = password;
            this.email = email;
            this.conectado = conectado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteNW.ServiceReference1.insertarUsuarioResponseBody Body;
        
        public insertarUsuarioResponse() {
        }
        
        public insertarUsuarioResponse(ClienteNW.ServiceReference1.insertarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertarUsuarioResponseBody {
        
        public insertarUsuarioResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public ClienteNW.ServiceReference1.eliminarUsuarioRequestBody Body;
        
        public eliminarUsuarioRequest() {
        }
        
        public eliminarUsuarioRequest(ClienteNW.ServiceReference1.eliminarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        public eliminarUsuarioRequestBody() {
        }
        
        public eliminarUsuarioRequestBody(string nickname) {
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteNW.ServiceReference1.eliminarUsuarioResponseBody Body;
        
        public eliminarUsuarioResponse() {
        }
        
        public eliminarUsuarioResponse(ClienteNW.ServiceReference1.eliminarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool eliminarUsuarioResult;
        
        public eliminarUsuarioResponseBody() {
        }
        
        public eliminarUsuarioResponseBody(bool eliminarUsuarioResult) {
            this.eliminarUsuarioResult = eliminarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public ClienteNW.ServiceReference1.buscarUsuarioRequestBody Body;
        
        public buscarUsuarioRequest() {
        }
        
        public buscarUsuarioRequest(ClienteNW.ServiceReference1.buscarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        public buscarUsuarioRequestBody() {
        }
        
        public buscarUsuarioRequestBody(string nickname) {
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteNW.ServiceReference1.buscarUsuarioResponseBody Body;
        
        public buscarUsuarioResponse() {
        }
        
        public buscarUsuarioResponse(ClienteNW.ServiceReference1.buscarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteNW.ServiceReference1.NodoABB buscarUsuarioResult;
        
        public buscarUsuarioResponseBody() {
        }
        
        public buscarUsuarioResponseBody(ClienteNW.ServiceReference1.NodoABB buscarUsuarioResult) {
            this.buscarUsuarioResult = buscarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public ClienteNW.ServiceReference1.ModificarUsuarioRequestBody Body;
        
        public ModificarUsuarioRequest() {
        }
        
        public ModificarUsuarioRequest(ClienteNW.ServiceReference1.ModificarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nicknameActual;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nicknameNuevo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int conectado;
        
        public ModificarUsuarioRequestBody() {
        }
        
        public ModificarUsuarioRequestBody(string nicknameActual, string nicknameNuevo, string password, string email, int conectado) {
            this.nicknameActual = nicknameActual;
            this.nicknameNuevo = nicknameNuevo;
            this.password = password;
            this.email = email;
            this.conectado = conectado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteNW.ServiceReference1.ModificarUsuarioResponseBody Body;
        
        public ModificarUsuarioResponse() {
        }
        
        public ModificarUsuarioResponse(ClienteNW.ServiceReference1.ModificarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModificarUsuarioResponseBody {
        
        public ModificarUsuarioResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enOrdenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="enOrden", Namespace="http://tempuri.org/", Order=0)]
        public ClienteNW.ServiceReference1.enOrdenRequestBody Body;
        
        public enOrdenRequest() {
        }
        
        public enOrdenRequest(ClienteNW.ServiceReference1.enOrdenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class enOrdenRequestBody {
        
        public enOrdenRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enOrdenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="enOrdenResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteNW.ServiceReference1.enOrdenResponseBody Body;
        
        public enOrdenResponse() {
        }
        
        public enOrdenResponse(ClienteNW.ServiceReference1.enOrdenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class enOrdenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string enOrdenResult;
        
        public enOrdenResponseBody() {
        }
        
        public enOrdenResponseBody(string enOrdenResult) {
            this.enOrdenResult = enOrdenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarHistorialJuegoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarHistorialJuego", Namespace="http://tempuri.org/", Order=0)]
        public ClienteNW.ServiceReference1.insertarHistorialJuegoRequestBody Body;
        
        public insertarHistorialJuegoRequest() {
        }
        
        public insertarHistorialJuegoRequest(ClienteNW.ServiceReference1.insertarHistorialJuegoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarHistorialJuegoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oponente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int desplegados;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int sobrevivientes;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int destruidas;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int gano;
        
        public insertarHistorialJuegoRequestBody() {
        }
        
        public insertarHistorialJuegoRequestBody(string nickname, string oponente, int desplegados, int sobrevivientes, int destruidas, int gano) {
            this.nickname = nickname;
            this.oponente = oponente;
            this.desplegados = desplegados;
            this.sobrevivientes = sobrevivientes;
            this.destruidas = destruidas;
            this.gano = gano;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarHistorialJuegoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarHistorialJuegoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteNW.ServiceReference1.insertarHistorialJuegoResponseBody Body;
        
        public insertarHistorialJuegoResponse() {
        }
        
        public insertarHistorialJuegoResponse(ClienteNW.ServiceReference1.insertarHistorialJuegoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertarHistorialJuegoResponseBody {
        
        public insertarHistorialJuegoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarEnOrtogonalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarEnOrtogonal", Namespace="http://tempuri.org/", Order=0)]
        public ClienteNW.ServiceReference1.insertarEnOrtogonalRequestBody Body;
        
        public insertarEnOrtogonalRequest() {
        }
        
        public insertarEnOrtogonalRequest(ClienteNW.ServiceReference1.insertarEnOrtogonalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarEnOrtogonalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int nivel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string unidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int movimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int alcance;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int dano;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int vida;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string columna;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int fila;
        
        public insertarEnOrtogonalRequestBody() {
        }
        
        public insertarEnOrtogonalRequestBody(int nivel, string unidad, int movimiento, int alcance, int dano, int vida, string columna, int fila) {
            this.nivel = nivel;
            this.unidad = unidad;
            this.movimiento = movimiento;
            this.alcance = alcance;
            this.dano = dano;
            this.vida = vida;
            this.columna = columna;
            this.fila = fila;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarEnOrtogonalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarEnOrtogonalResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteNW.ServiceReference1.insertarEnOrtogonalResponseBody Body;
        
        public insertarEnOrtogonalResponse() {
        }
        
        public insertarEnOrtogonalResponse(ClienteNW.ServiceReference1.insertarEnOrtogonalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarEnOrtogonalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool insertarEnOrtogonalResult;
        
        public insertarEnOrtogonalResponseBody() {
        }
        
        public insertarEnOrtogonalResponseBody(bool insertarEnOrtogonalResult) {
            this.insertarEnOrtogonalResult = insertarEnOrtogonalResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceNavalWarsSoapChannel : ClienteNW.ServiceReference1.ServiceNavalWarsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceNavalWarsSoapClient : System.ServiceModel.ClientBase<ClienteNW.ServiceReference1.ServiceNavalWarsSoap>, ClienteNW.ServiceReference1.ServiceNavalWarsSoap {
        
        public ServiceNavalWarsSoapClient() {
        }
        
        public ServiceNavalWarsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceNavalWarsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNavalWarsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNavalWarsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void iniciarEstructuras() {
            base.Channel.iniciarEstructuras();
        }
        
        public System.Threading.Tasks.Task iniciarEstructurasAsync() {
            return base.Channel.iniciarEstructurasAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteNW.ServiceReference1.logearUsuarioResponse ClienteNW.ServiceReference1.ServiceNavalWarsSoap.logearUsuario(ClienteNW.ServiceReference1.logearUsuarioRequest request) {
            return base.Channel.logearUsuario(request);
        }
        
        public string logearUsuario(string nickname) {
            ClienteNW.ServiceReference1.logearUsuarioRequest inValue = new ClienteNW.ServiceReference1.logearUsuarioRequest();
            inValue.Body = new ClienteNW.ServiceReference1.logearUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            ClienteNW.ServiceReference1.logearUsuarioResponse retVal = ((ClienteNW.ServiceReference1.ServiceNavalWarsSoap)(this)).logearUsuario(inValue);
            return retVal.Body.logearUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteNW.ServiceReference1.logearUsuarioResponse> ClienteNW.ServiceReference1.ServiceNavalWarsSoap.logearUsuarioAsync(ClienteNW.ServiceReference1.logearUsuarioRequest request) {
            return base.Channel.logearUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteNW.ServiceReference1.logearUsuarioResponse> logearUsuarioAsync(string nickname) {
            ClienteNW.ServiceReference1.logearUsuarioRequest inValue = new ClienteNW.ServiceReference1.logearUsuarioRequest();
            inValue.Body = new ClienteNW.ServiceReference1.logearUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            return ((ClienteNW.ServiceReference1.ServiceNavalWarsSoap)(this)).logearUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteNW.ServiceReference1.insertarUsuarioResponse ClienteNW.ServiceReference1.ServiceNavalWarsSoap.insertarUsuario(ClienteNW.ServiceReference1.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuario(request);
        }
        
        public void insertarUsuario(string nickname, string password, string email, int conectado) {
            ClienteNW.ServiceReference1.insertarUsuarioRequest inValue = new ClienteNW.ServiceReference1.insertarUsuarioRequest();
            inValue.Body = new ClienteNW.ServiceReference1.insertarUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.conectado = conectado;
            ClienteNW.ServiceReference1.insertarUsuarioResponse retVal = ((ClienteNW.ServiceReference1.ServiceNavalWarsSoap)(this)).insertarUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteNW.ServiceReference1.insertarUsuarioResponse> ClienteNW.ServiceReference1.ServiceNavalWarsSoap.insertarUsuarioAsync(ClienteNW.ServiceReference1.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteNW.ServiceReference1.insertarUsuarioResponse> insertarUsuarioAsync(string nickname, string password, string email, int conectado) {
            ClienteNW.ServiceReference1.insertarUsuarioRequest inValue = new ClienteNW.ServiceReference1.insertarUsuarioRequest();
            inValue.Body = new ClienteNW.ServiceReference1.insertarUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.conectado = conectado;
            return ((ClienteNW.ServiceReference1.ServiceNavalWarsSoap)(this)).insertarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteNW.ServiceReference1.eliminarUsuarioResponse ClienteNW.ServiceReference1.ServiceNavalWarsSoap.eliminarUsuario(ClienteNW.ServiceReference1.eliminarUsuarioRequest request) {
            return base.Channel.eliminarUsuario(request);
        }
        
        public bool eliminarUsuario(string nickname) {
            ClienteNW.ServiceReference1.eliminarUsuarioRequest inValue = new ClienteNW.ServiceReference1.eliminarUsuarioRequest();
            inValue.Body = new ClienteNW.ServiceReference1.eliminarUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            ClienteNW.ServiceReference1.eliminarUsuarioResponse retVal = ((ClienteNW.ServiceReference1.ServiceNavalWarsSoap)(this)).eliminarUsuario(inValue);
            return retVal.Body.eliminarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteNW.ServiceReference1.eliminarUsuarioResponse> ClienteNW.ServiceReference1.ServiceNavalWarsSoap.eliminarUsuarioAsync(ClienteNW.ServiceReference1.eliminarUsuarioRequest request) {
            return base.Channel.eliminarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteNW.ServiceReference1.eliminarUsuarioResponse> eliminarUsuarioAsync(string nickname) {
            ClienteNW.ServiceReference1.eliminarUsuarioRequest inValue = new ClienteNW.ServiceReference1.eliminarUsuarioRequest();
            inValue.Body = new ClienteNW.ServiceReference1.eliminarUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            return ((ClienteNW.ServiceReference1.ServiceNavalWarsSoap)(this)).eliminarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteNW.ServiceReference1.buscarUsuarioResponse ClienteNW.ServiceReference1.ServiceNavalWarsSoap.buscarUsuario(ClienteNW.ServiceReference1.buscarUsuarioRequest request) {
            return base.Channel.buscarUsuario(request);
        }
        
        public ClienteNW.ServiceReference1.NodoABB buscarUsuario(string nickname) {
            ClienteNW.ServiceReference1.buscarUsuarioRequest inValue = new ClienteNW.ServiceReference1.buscarUsuarioRequest();
            inValue.Body = new ClienteNW.ServiceReference1.buscarUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            ClienteNW.ServiceReference1.buscarUsuarioResponse retVal = ((ClienteNW.ServiceReference1.ServiceNavalWarsSoap)(this)).buscarUsuario(inValue);
            return retVal.Body.buscarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteNW.ServiceReference1.buscarUsuarioResponse> ClienteNW.ServiceReference1.ServiceNavalWarsSoap.buscarUsuarioAsync(ClienteNW.ServiceReference1.buscarUsuarioRequest request) {
            return base.Channel.buscarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteNW.ServiceReference1.buscarUsuarioResponse> buscarUsuarioAsync(string nickname) {
            ClienteNW.ServiceReference1.buscarUsuarioRequest inValue = new ClienteNW.ServiceReference1.buscarUsuarioRequest();
            inValue.Body = new ClienteNW.ServiceReference1.buscarUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            return ((ClienteNW.ServiceReference1.ServiceNavalWarsSoap)(this)).buscarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteNW.ServiceReference1.ModificarUsuarioResponse ClienteNW.ServiceReference1.ServiceNavalWarsSoap.ModificarUsuario(ClienteNW.ServiceReference1.ModificarUsuarioRequest request) {
            return base.Channel.ModificarUsuario(request);
        }
        
        public void ModificarUsuario(string nicknameActual, string nicknameNuevo, string password, string email, int conectado) {
            ClienteNW.ServiceReference1.ModificarUsuarioRequest inValue = new ClienteNW.ServiceReference1.ModificarUsuarioRequest();
            inValue.Body = new ClienteNW.ServiceReference1.ModificarUsuarioRequestBody();
            inValue.Body.nicknameActual = nicknameActual;
            inValue.Body.nicknameNuevo = nicknameNuevo;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.conectado = conectado;
            ClienteNW.ServiceReference1.ModificarUsuarioResponse retVal = ((ClienteNW.ServiceReference1.ServiceNavalWarsSoap)(this)).ModificarUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteNW.ServiceReference1.ModificarUsuarioResponse> ClienteNW.ServiceReference1.ServiceNavalWarsSoap.ModificarUsuarioAsync(ClienteNW.ServiceReference1.ModificarUsuarioRequest request) {
            return base.Channel.ModificarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteNW.ServiceReference1.ModificarUsuarioResponse> ModificarUsuarioAsync(string nicknameActual, string nicknameNuevo, string password, string email, int conectado) {
            ClienteNW.ServiceReference1.ModificarUsuarioRequest inValue = new ClienteNW.ServiceReference1.ModificarUsuarioRequest();
            inValue.Body = new ClienteNW.ServiceReference1.ModificarUsuarioRequestBody();
            inValue.Body.nicknameActual = nicknameActual;
            inValue.Body.nicknameNuevo = nicknameNuevo;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.conectado = conectado;
            return ((ClienteNW.ServiceReference1.ServiceNavalWarsSoap)(this)).ModificarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteNW.ServiceReference1.enOrdenResponse ClienteNW.ServiceReference1.ServiceNavalWarsSoap.enOrden(ClienteNW.ServiceReference1.enOrdenRequest request) {
            return base.Channel.enOrden(request);
        }
        
        public string enOrden() {
            ClienteNW.ServiceReference1.enOrdenRequest inValue = new ClienteNW.ServiceReference1.enOrdenRequest();
            inValue.Body = new ClienteNW.ServiceReference1.enOrdenRequestBody();
            ClienteNW.ServiceReference1.enOrdenResponse retVal = ((ClienteNW.ServiceReference1.ServiceNavalWarsSoap)(this)).enOrden(inValue);
            return retVal.Body.enOrdenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteNW.ServiceReference1.enOrdenResponse> ClienteNW.ServiceReference1.ServiceNavalWarsSoap.enOrdenAsync(ClienteNW.ServiceReference1.enOrdenRequest request) {
            return base.Channel.enOrdenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteNW.ServiceReference1.enOrdenResponse> enOrdenAsync() {
            ClienteNW.ServiceReference1.enOrdenRequest inValue = new ClienteNW.ServiceReference1.enOrdenRequest();
            inValue.Body = new ClienteNW.ServiceReference1.enOrdenRequestBody();
            return ((ClienteNW.ServiceReference1.ServiceNavalWarsSoap)(this)).enOrdenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteNW.ServiceReference1.insertarHistorialJuegoResponse ClienteNW.ServiceReference1.ServiceNavalWarsSoap.insertarHistorialJuego(ClienteNW.ServiceReference1.insertarHistorialJuegoRequest request) {
            return base.Channel.insertarHistorialJuego(request);
        }
        
        public void insertarHistorialJuego(string nickname, string oponente, int desplegados, int sobrevivientes, int destruidas, int gano) {
            ClienteNW.ServiceReference1.insertarHistorialJuegoRequest inValue = new ClienteNW.ServiceReference1.insertarHistorialJuegoRequest();
            inValue.Body = new ClienteNW.ServiceReference1.insertarHistorialJuegoRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.oponente = oponente;
            inValue.Body.desplegados = desplegados;
            inValue.Body.sobrevivientes = sobrevivientes;
            inValue.Body.destruidas = destruidas;
            inValue.Body.gano = gano;
            ClienteNW.ServiceReference1.insertarHistorialJuegoResponse retVal = ((ClienteNW.ServiceReference1.ServiceNavalWarsSoap)(this)).insertarHistorialJuego(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteNW.ServiceReference1.insertarHistorialJuegoResponse> ClienteNW.ServiceReference1.ServiceNavalWarsSoap.insertarHistorialJuegoAsync(ClienteNW.ServiceReference1.insertarHistorialJuegoRequest request) {
            return base.Channel.insertarHistorialJuegoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteNW.ServiceReference1.insertarHistorialJuegoResponse> insertarHistorialJuegoAsync(string nickname, string oponente, int desplegados, int sobrevivientes, int destruidas, int gano) {
            ClienteNW.ServiceReference1.insertarHistorialJuegoRequest inValue = new ClienteNW.ServiceReference1.insertarHistorialJuegoRequest();
            inValue.Body = new ClienteNW.ServiceReference1.insertarHistorialJuegoRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.oponente = oponente;
            inValue.Body.desplegados = desplegados;
            inValue.Body.sobrevivientes = sobrevivientes;
            inValue.Body.destruidas = destruidas;
            inValue.Body.gano = gano;
            return ((ClienteNW.ServiceReference1.ServiceNavalWarsSoap)(this)).insertarHistorialJuegoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteNW.ServiceReference1.insertarEnOrtogonalResponse ClienteNW.ServiceReference1.ServiceNavalWarsSoap.insertarEnOrtogonal(ClienteNW.ServiceReference1.insertarEnOrtogonalRequest request) {
            return base.Channel.insertarEnOrtogonal(request);
        }
        
        public bool insertarEnOrtogonal(int nivel, string unidad, int movimiento, int alcance, int dano, int vida, string columna, int fila) {
            ClienteNW.ServiceReference1.insertarEnOrtogonalRequest inValue = new ClienteNW.ServiceReference1.insertarEnOrtogonalRequest();
            inValue.Body = new ClienteNW.ServiceReference1.insertarEnOrtogonalRequestBody();
            inValue.Body.nivel = nivel;
            inValue.Body.unidad = unidad;
            inValue.Body.movimiento = movimiento;
            inValue.Body.alcance = alcance;
            inValue.Body.dano = dano;
            inValue.Body.vida = vida;
            inValue.Body.columna = columna;
            inValue.Body.fila = fila;
            ClienteNW.ServiceReference1.insertarEnOrtogonalResponse retVal = ((ClienteNW.ServiceReference1.ServiceNavalWarsSoap)(this)).insertarEnOrtogonal(inValue);
            return retVal.Body.insertarEnOrtogonalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteNW.ServiceReference1.insertarEnOrtogonalResponse> ClienteNW.ServiceReference1.ServiceNavalWarsSoap.insertarEnOrtogonalAsync(ClienteNW.ServiceReference1.insertarEnOrtogonalRequest request) {
            return base.Channel.insertarEnOrtogonalAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteNW.ServiceReference1.insertarEnOrtogonalResponse> insertarEnOrtogonalAsync(int nivel, string unidad, int movimiento, int alcance, int dano, int vida, string columna, int fila) {
            ClienteNW.ServiceReference1.insertarEnOrtogonalRequest inValue = new ClienteNW.ServiceReference1.insertarEnOrtogonalRequest();
            inValue.Body = new ClienteNW.ServiceReference1.insertarEnOrtogonalRequestBody();
            inValue.Body.nivel = nivel;
            inValue.Body.unidad = unidad;
            inValue.Body.movimiento = movimiento;
            inValue.Body.alcance = alcance;
            inValue.Body.dano = dano;
            inValue.Body.vida = vida;
            inValue.Body.columna = columna;
            inValue.Body.fila = fila;
            return ((ClienteNW.ServiceReference1.ServiceNavalWarsSoap)(this)).insertarEnOrtogonalAsync(inValue);
        }
    }
}
